# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/crystallang/crystal/
image: "crystallang/crystal:latest"

# Cache shards in between builds
cache:
  paths:
    - lib
    - bin

before_script:
  - crystal -v # Print out Crystal version for debugging

format:
  script:
    - shards
    - crystal tool format --check

style:
  script:
    - shards
    - bin/ameba

pages:
  stage: deploy
  script:
    - crystal docs
    - mv docs/ public/
  artifacts:
    paths:
      - public
  only:
    - master
