files: ./src/**/*.cr
run: crystal spec --rand
---
files: ./src/**/*.cr
run: bin/ameba %file%
---
files: ./spec/**/*.cr
run: crystal spec --rand %file%
---
files: ./src/**/*.cr
run: crystal tool format %file%
---
files: ./spec/**/*.cr
run: crystal tool format %file%
---
files: ./examples/**/*.cr
run: crystal tool format %file%
---
files: ./shard.yml
run: shards
